### ISSUE TITLE
CNAMEの設定について

### ISSUE THREAD

**Issue by raito417** [raito417/kurajoHP#2]
cnameというのは[http://cloudjoshi.webcrow.jp/](url)で[https://raito417.github.io/cloudjogakuen/](url)の内容を表示するということでいいのでしょうか
また、その場合のCNAMEファイルはウェブクロウに置けばいいのでしょうか

CNAMEファイルの記述は
`https://raito417.github.io/cloudjogakuen/　IN CNAME http://cloudjoshi.webcrow.jp/`
としています。

**Comment by tyoudamui** [comment]
あっほらgithubでユーザー名丸出しだとググラビリティ低いから、ドメインつけようって話
あとついでだからjyogakuin.cloudを供養してってだけでした

**Comment by raito417** [comment]
ウェブクロウの方はgoogleのクローラに登録しておきましたので検索結果には表示されると思います
制作が一段落するごとにウェブクロウと同期させようと思っています

**Comment by chusaka** [comment]
もう解決してるのかしら？
いまいち何をやりたいのか分からないけど、

  ・ゾーンファイルは そのドメインを持っているサーバで設定(ドメイン取得したところで設定するとか)
  ・CNAMEは書くとしたら
      raito417.github.io. IN CNAME cloudjoshi.webcrow.jp.
      みたいにドメイン名を書く

じゃないかな？

#ちなみにissueには「何がしたくて何が問題となっているのか」をわかるように書いておくといいっすよ

**Comment by tyoudamui** [comment]
コンテンツ同期の仕組みちゃんとしてれば問題ないかな

githubpagesだと個人のアカウントが出ちゃうから、個人的にはプライバシーなとこが気になるだけでした

れんさばのドメインならdns触れないぽいし難しそう

**Comment by raito417** [comment]
皆さんありがとうございます。CNAMEは諦めることにします。
githubはコード公開の場として利用しようと思います
